name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Fix Structure and Init
        run: |
          # 1. إنشاء مجلد www رسمي
          mkdir -p www
          # 2. نقل كل ملفات المشروع داخل المجلد
          # نستخدم find لنقل الملفات مع الحفاظ على الهيكلية
          find . -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" -o -name "*.json" \) -exec cp {} www/ \;
          # 3. إنشاء ملف إعدادات جديد يشير إلى www
          echo '{"appId": "com.youssefmosaad.soralnaharda", "appName": "سعر النهاردة", "webDir": "www", "bundledWebRuntime": false}' > capacitor.config.json
      - name: Build and Sync
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android
      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
