name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor/assets --save-dev
      - name: Force Config and Assets
        run: |
          # إنشاء ملف الإعدادات برمجياً لضمان وجود الـ appId
          echo '{"appId": "com.youssefmosaad.soralnaharda", "appName": "سعر النهاردة", "webDir": "www", "bundledWebRuntime": false}' > capacitor.config.json
          # توليد الأيقونات
          npx @capacitor/assets generate
      - name: Build Android
        run: |
          npx cap add android || true
          npx cap sync android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
