name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Initialize Capacitor
        # هذا الأمر يقوم بإنشاء الإعدادات برمجياً لضمان عدم وجود أخطاء في الملف المرفوع
        run: |
          npx cap init searyelnaharda com.youssefmosaad.soralnaharda --web-dir .
      - name: Add Android Platform
        run: |
          npx cap add android
          npx cap sync android
      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
